export const ADD_PROJECT = "ADD_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const DEFINIR_PROJECTS = "DEFINIR_PROJECTS";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
